
DROP DATABASE IF EXISTS hstestdb4;
CREATE DATABASE hstestdb4;
USE hstestdb4;

CREATE TABLE HTML (
 uuid CHAR(36) NOT NULL,
 content TEXT NOT NULL,
 PRIMARY KEY (uuid));

CREATE TABLE XML (
 uuid CHAR(36) NOT NULL,
 content TEXT NOT NULL,
  PRIMARY KEY (uuid));

CREATE TABLE XSD (
 uuid CHAR(36) NOT NULL,
 content TEXT NOT NULL,
  PRIMARY KEY (uuid));
  
CREATE TABLE XSLT (
 uuid CHAR(36) NOT NULL,
 content TEXT NOT NULL,
 xsd CHAR(36),
  PRIMARY KEY (uuid));

GRANT ALL PRIVILEGES ON hstestdb4.* TO hsdb@'%';
FLUSH PRIVILEGES;
  